CREATE OR ALTER VIEW dbo.DimCalendarView
AS
SELECT [DateKey]
      ,[DateValue]
      ,[MonthNameNational]          AS  [English Month Name]
      ,[DayNameNational]            AS  [English Day Name]
      ,[MonthNameLocal]             AS  [Greek Month Name]
      ,[DayNameLocal]               AS  [Greek Day Name]
      ,[IsWeekend]                  AS  [Is Weekend Day]
      ,[IsLeapYear]                 AS  [Is Leap Year]
      ,[CYYear]                     AS  [Calendar Year]
      ,[CYYearName]                 AS  [Calendar Year Name]
      ,[CYSemester]                 AS  [Calendar Year Semester]
      ,[CYSemesterName]             AS  [Calendar Year Semester Name]
      ,[CYQuarter]                  AS  [Calendar Year Quarter]
      ,[CYQuarterName]              AS  [Calendar Year Quarter Name]
      ,[CYSemesterQuarter]          AS  [Calendar Year Semester Quarter]
      ,[CYMonth]                    AS  [Calendar Year Month]
      ,[CYMonthName]                AS  [Calendar Year Month Name]
      ,[CYSemesterMonth]            AS  [Calendar Year Semester Month]
      ,[CYQuarterMonth]             AS  [Calendar Year Quarter Month]
      ,[CYWeek]                     AS  [Calendar Year Week]
      ,[CYWeekName]                 AS  [Calendar Year Week Name]
      ,[CYSemesterWeek]             AS  [Calendar Year Semester Week]
      ,[CYQuarterWeek]              AS  [Calendar Year Quarter Week]
      ,[CYMonthWeek]                AS  [Calendar Year Month Week]
      ,[CYDay]                      AS  [Calendar Year Day Number]
      ,[CYSemesterDay]              AS  [Calendar Year Semester Day Number]
      ,[CYQuarterDay]               AS  [Calendar Year Quarter Day Number]
      ,[CYMonthDay]                 AS  [Calendar Year Month Day Number]
      ,[CYWeekDay]                  AS  [Calendar Year Week Day Number]
      ,[CYFirstDate]                AS  [Calendar Year First Date]
      ,[CYLastDate]                 AS  [Calendar Year Last Date]
      ,[FYYear]                     AS  [Fiscal Year]
      ,[FYYearName]                 AS  [Fiscal Year Name]
      ,[FYSemester]                 AS  [Fiscal Year Semester]
      ,[FYSemesterName]             AS  [Fiscal Year Semester Name]
      ,[FYQuarter]                  AS  [Fiscal Year Quarter]
      ,[FYSemesterQuarter]          AS  [Fiscal Year Quarter Name]
      ,[FYMonth]                    AS  [Fiscal Year Month]
      ,[FYMonthName]                AS  [Fiscal Year Month Name] 
      ,[FYSemesterMonth]            AS  [Fiscal Year Semester Month]
      ,[FYQuarterMonth]             AS  [Fiscal Year Quarter Month]
      ,[FYWeek]                     AS  [Fiscal Year Week]
      ,[FYWeekName]                 AS  [Fiscal Year Week Name]
      ,[FYSemesterWeek]             AS  [Fiscal Year Semester Week]
      ,[FYQuarterWeek]              AS  [Fiscal Year Quarter Week]
      ,[FYMonthWeek]                AS  [Fiscal Year Month Week]
      ,[FYDay]                      AS  [Fiscal Year Day Number]
      ,[FYSemesterDay]              AS  [Fiscal Year Semester Day Number]
      ,[FYQuarterDay]               AS  [Fiscal Year Quarter Day Number]
      ,[FYMonthDay]                 AS  [Fiscal Year Month Day Number]
      ,[FYWeekDay]                  AS  [Fiscal Year Week Day Number]
      ,[FYFirstDate]                AS  [Fiscal Year First Date]
      ,[FYLastDate]                 AS  [Fiscal Year Last Date]
      ,[ISOYear]                    AS  [ISO Year]
      ,[ISOYearName]                AS  [ISO Year Name]
      ,[ISOSemester]                AS  [ISO Year Semester]
      ,[ISOSemesterName]            AS  [ISO Year Semester Name]
      ,[ISOQuarter]                 AS  [ISO Year Quarter]
      ,[ISOQuarterName]             AS  [ISO Year Quarter Name]
      ,[ISOSemesterQuarter]         AS  [ISO Year Semester Quarter]
      ,[ISOMonth]                   AS  [ISO Year Month]
      ,[ISOMonthName]               AS  [ISO Year Month Name]
      ,[ISOSemesterMonth]           AS  [ISO Year Semester Month]
      ,[ISOQuarterMonth]            AS  [ISO Year Quarter Month]
      ,[ISOWeek]                    AS  [ISO Year Week]
      ,[ISOWeekName]                AS  [ISO Year Week Name]
      ,[ISOSemesterWeek]            AS  [ISO Year Semester Week]
      ,[ISOQuarterWeek]             AS  [ISO Year Quarter Week]
      ,[ISOMonthWeek]               AS  [ISO Year Month Week]
      ,[ISODay]                     AS  [ISO Year Day Number]
      ,[ISOSemesterDay]             AS  [ISO Year Semester Day Number]
      ,[ISOQuarterDay]              AS  [ISO Year Quarter Day Number]
      ,[ISOMonthDay]                AS  [ISO Year Month Day Number]
      ,[ISOWeekDay]                 AS  [ISO Year Week Day Number]
      ,[ISODayName]                 AS  [ISO Year Day Name]
      ,[ISOFirstDate]               AS  [ISO Year First Date]
      ,[ISOLastDate]                AS  [ISO Year Last Date]
      ,[IsNationalHoliday]          AS  [Is National Holiday]
      ,[IsLocalHoliday]             AS  [Is Greek Holiday]
      ,[HolidayName]                AS  [Holiday Name]
  FROM [dbo].[DimCalendar]
GO


SELECT * FROM dbo.DimCalendarView;