SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE dbo.DimCalendar(
	DateKey                 int             NOT NULL,
	DateValue               date            NOT NULL,
	MonthNameNational       nvarchar(15)    NOT NULL,
	DayNameNational         nvarchar(15)    NOT NULL,
	MonthNameLocal          nvarchar(15)    NOT NULL,
	DayNameLocal            nvarchar(15)    NOT NULL,
	IsWeekend               bit             NOT NULL,
	IsLeapYear              bit             NOT NULL,
	CYYear                  int             NOT NULL,
	CYYearName              nvarchar(15)    NOT NULL,
	CYSemester              int             NOT NULL,
	CYSemesterName          nvarchar(15)    NOT NULL,
	CYQuarter               int             NOT NULL,
	CYQuarterName           nvarchar(15)    NOT NULL,
	CYSemesterQuarter       int             NOT NULL,
	CYMonth                 int             NOT NULL,
	CYMonthName             nvarchar(15)    NOT NULL,
	CYSemesterMonth         int             NOT NULL,
	CYQuarterMonth          int             NOT NULL,
	CYWeek                  int             NOT NULL,
	CYWeekName              nvarchar(15)    NOT NULL,
	CYSemesterWeek          int             NOT NULL,
	CYQuarterWeek           int             NOT NULL,
	CYMonthWeek             int             NOT NULL,
	CYDay                   int             NOT NULL,
	CYSemesterDay           int             NOT NULL,
	CYQuarterDay            int             NOT NULL,
	CYMonthDay              int             NOT NULL,
	CYWeekDay               int             NOT NULL,
	CYFirstDate             date            NOT NULL,
	CYLastDate              date            NOT NULL,
	FYYear                  int             NOT NULL,
	FYYearName              nvarchar(15)    NOT NULL,
	FYSemester              int             NOT NULL,
	FYSemesterName          nvarchar(15)    NOT NULL,
	FYQuarter               int             NOT NULL,
	FYSemesterQuarter       int             NOT NULL,
	FYMonth                 int             NOT NULL,
	FYMonthName             nvarchar(15)    NOT NULL,
	FYSemesterMonth         int             NOT NULL,
	FYQuarterMonth          int             NOT NULL,
	FYWeek                  int             NOT NULL,
	FYWeekName              nvarchar(15)    NOT NULL,
	FYSemesterWeek          int             NOT NULL,
	FYQuarterWeek           int             NOT NULL,
	FYMonthWeek             int             NOT NULL,
	FYDay                   int             NOT NULL,
	FYSemesterDay           int             NOT NULL,
	FYQuarterDay            int             NOT NULL,
	FYMonthDay              int             NOT NULL,
	FYWeekDay               int             NOT NULL,
	FYFirstDate             date            NOT NULL,
	FYLastDate              date            NOT NULL,
	ISOYear                 int             NOT NULL,
	ISOYearName             nvarchar(15)    NOT NULL,
	ISOSemester             int             NOT NULL,
	ISOSemesterName         nvarchar(15)    NOT NULL,
	ISOQuarter              int             NOT NULL,
	ISOQuarterName          nvarchar(15)    NOT NULL,
	ISOSemesterQuarter      int             NOT NULL,
	ISOMonth                int             NOT NULL,
	ISOMonthName            nvarchar(15)    NOT NULL,
	ISOSemesterMonth        int             NOT NULL,
	ISOQuarterMonth         int             NOT NULL,
	ISOWeek                 int             NOT NULL,
	ISOWeekName             nvarchar(15)    NOT NULL,
	ISOSemesterWeek         int             NOT NULL,
	ISOQuarterWeek          int             NOT NULL,
	ISOMonthWeek            int             NOT NULL,
	ISODay                  int             NOT NULL,
	ISOSemesterDay          int             NOT NULL,
	ISOQuarterDay           int             NOT NULL,
	ISOMonthDay             int             NOT NULL,
	ISOWeekDay              int             NOT NULL,
	ISODayName              nvarchar(15)    NOT NULL,
	ISOFirstDate            date            NOT NULL,
	ISOLastDate             date            NOT NULL,
	IsNationalHoliday       bit             NOT NULL,
	IsLocalHoliday          bit             NOT NULL,
	HolidayName             nvarchar(100)   NULL
) 
GO

ALTER TABLE dbo.DimCalendar
ADD CONSTRAINT PK_DimCalendar PRIMARY KEY CLUSTERED (DateKey)
GO
